from __future__ import annotations

from .sandkings_v5 import SandkingsPageBeat

PAGE_BEATS_24: tuple[SandkingsPageBeat, ...] = (
    SandkingsPageBeat(
        turning_point="克雷斯归来，发现水虎鱼与兀鹰都已死亡",
        purpose="以死亡的收藏建立克雷斯的厌倦、财富与控制欲",
        shot="gothic cinematic wide shot",
        narration="西蒙·克雷斯回到巴尔德尔星球时，迎接他的只有腐败的收藏和更深的无聊。",
        sfx="嗡——",
        visual_tags=(
            "retrofuturist alien manor at night",
            "dead aquarium behind cracked glass",
            "empty exotic bird enclosure",
            "panoramic window above a hostile neon city",
            "oppressive gothic shadows",
        ),
        characters=("西蒙·克雷斯",),
        actions=("stands between the dead aquarium and empty cage deciding to seek a new thrill",),
        expressions=("cold contemptuous boredom",),
    ),
    SandkingsPageBeat(
        turning_point="克雷斯走进彩虹大道尽头的沃-希德进口商店",
        purpose="让诱惑以神秘交易的形式出现",
        shot="extreme low-angle doorway shot",
        narration="彩虹大道尽头，一扇从未见过的门为他打开。门后，贾拉·沃早已在等。",
        sfx="吱呀",
        visual_tags=(
            "mysterious alien pet shop entrance",
            "towering shelves of sealed biological curiosities",
            "smoke and hanging bone-like ornaments",
            "narrow pool of white doorway light",
        ),
        characters=("西蒙·克雷斯", "贾拉·沃"),
        actions=(
            "steps through the doorway with entitled curiosity",
            "waits motionless beside a veiled glass habitat",
        ),
        expressions=("skeptical interest", "knowing unreadable calm"),
        relationship_action="the merchant silently measures the arrogant collector",
    ),
    SandkingsPageBeat(
        turning_point="沃揭开四窝沙王、四座城堡与地下沙母",
        purpose="第一次完整呈现沙王的战争、建筑与崇拜能力",
        shot="dramatic overhead reveal",
        narration="沃揭开帷幕: 四座微型王国，四支军队，以及沙层下四张永不满足的巨口。",
        sfx="沙沙沙",
        visual_tags=(
            "enormous glass habitat divided into four kingdoms",
            "four insect colonies distinguished by solid black pale white "
            "crosshatched and stippled markings",
            "organic sand castles with carved faces",
            "four pulsing alien maws visible beneath cutaway sand",
            "miniature armies marching in formation",
        ),
        characters=("西蒙·克雷斯", "贾拉·沃"),
        actions=(
            "leans over the habitat with possessive fascination",
            "raises one warning hand above the four living kingdoms",
        ),
        expressions=("greedy astonishment", "grave warning expression"),
        relationship_action=(
            "the merchant reveals a living civilization to a man who sees only property"
        ),
    ),
    SandkingsPageBeat(
        turning_point="克雷斯买下四窝休眠沙王并装进旧水虎鱼缸",
        purpose="把危险从商店带入克雷斯的私人领地",
        shot="wide installation tableau",
        narration="他买下了全部四窝。旧鱼缸被改造成世界，而克雷斯把自己安放在世界之上。",
        sfx="咔嗒",
        visual_tags=(
            "private alien manor laboratory",
            "workers reduced to distant silhouettes behind glass",
            "four sealed nesting chambers lowered into a vast converted aquarium",
            "control console and overhead feeding mechanisms",
            "collector looming above the installation",
        ),
        characters=("西蒙·克雷斯", "贾拉·沃"),
        actions=(
            "signs the purchase while watching the dormant nests descend",
            "points to the habitat controls while giving a final warning",
        ),
        expressions=("triumphant ownership", "stern concern"),
        relationship_action="the buyer ignores the seller's final conditions",
    ),
    SandkingsPageBeat(
        turning_point="沙王孵化并在一夜之间建起第一批城堡",
        purpose="表现群体智慧以及快速成长的异常",
        shot="macro-to-wide forced-perspective shot",
        narration="卵壳裂开后，工沙没有四处乱爬。它们列队、测量、挖掘，像一支记得文明的军队。",
        sfx="喀啦",
        visual_tags=(
            "freshly hatched alien insect workers in geometric formation",
            "miniature construction lines crossing wet sand",
            "four rapidly rising organic fortresses",
            "giant observing human eye reflected in habitat glass",
            "intricate engineering detail",
        ),
        characters=("西蒙·克雷斯",),
        actions=("presses close to the glass while the colonies construct beneath his gaze",),
        expressions=("childlike fascination turning possessive",),
    ),
    SandkingsPageBeat(
        turning_point="克雷斯把自己的全息头像赐给沙王崇拜",
        purpose="确立伪神主题和反复出现的人脸城堡母题",
        shot="monumental worm's-eye composition",
        narration="他把自己的脸悬在天空。很快，每一道城墙都学会了雕刻那张脸。",
        sfx="滋——",
        visual_tags=(
            "giant holographic male face filling the artificial sky",
            "four sand castles carving the same severe human idol",
            "tiny insect armies kneeling toward the projection",
            "collector posed like a false god above the glass",
            "religious horror imagery",
        ),
        characters=("西蒙·克雷斯",),
        actions=("raises both hands beneath his enormous holographic likeness",),
        expressions=("ecstatic narcissistic smile",),
    ),
    SandkingsPageBeat(
        turning_point="克雷斯断粮两天，黑沙王捕食橙色同类并引爆战争",
        purpose="让主角第一次主动制造饥饿与屠杀",
        shot="violent top-down battlefield shot",
        narration="两天没有食物。第一只黑色工沙咬住橙色同类时，克雷斯终于看见了他想要的战争。",
        sfx="咔嚓!",
        visual_tags=(
            "miniature alien battlefield inside glass habitat",
            "solid-black insect legion ambushing stippled orange colony",
            "collapsed bridge between two sand fortresses",
            "hundreds of tiny soldiers surging in disciplined ranks",
            "giant human hand withholding food above them",
        ),
        characters=("西蒙·克雷斯",),
        actions=("holds the sealed food control above the war while taking notes",),
        expressions=("proud cruel delight",),
    ),
    SandkingsPageBeat(
        turning_point="克雷斯在聚会上把饥饿战争变成下注表演",
        purpose="公开他的残酷，并让卡茜成为道德反面",
        shot="high-angle decadent party tableau",
        narration="宾客下注，残羹落下，四国在玻璃里互相撕碎。卡茜只说了一个词: 恶心。",
        sfx="铿!",
        visual_tags=(
            "decadent science fiction cocktail party",
            "glass habitat battlefield as a gambling arena",
            "wealthy guests reduced to shadowy spectators",
            "insect armies fighting over falling scraps",
            "dramatic diagonal separation between host and dissenter",
        ),
        characters=("西蒙·克雷斯", "卡茜·穆雷"),
        actions=(
            "raises a crystal glass over the miniature slaughter",
            "turns away from the arena with clenched fists",
        ),
        expressions=("cruel celebratory grin", "furious moral disgust"),
        relationship_action="former lovers confront each other across the living arena",
    ),
    SandkingsPageBeat(
        turning_point="数月战争游戏后，橙色王国被长期饥饿逼向灭绝",
        purpose="用时间蒙太奇表现虐待常态化与橙色伏笔",
        shot="symbolic time-lapse montage",
        narration="数月过去，赌注越来越大，橙色城堡却越来越小。克雷斯从未问过它们去了哪里。",
        sfx="滴答",
        visual_tags=(
            "three overlapping phases of the same habitat",
            "gambling tokens and signed debt notes around the glass",
            "shrinking stippled-orange fortress surrounded by larger rival kingdoms",
            "empty orange tunnels leading beyond the visible habitat",
            "calendar shadows sweeping across the scene",
        ),
        characters=("西蒙·克雷斯",),
        actions=("counts winnings while ignoring the nearly abandoned orange colony",),
        expressions=("careless smug satisfaction",),
    ),
    SandkingsPageBeat(
        turning_point="卡萨蒂沙漠蜘蛛冲进红色城堡",
        purpose="把游戏升级成巨兽攻城并展示沙王的集体战术",
        shot="extreme forced-perspective action shot",
        narration="拉吉斯带来一头沙漠蜘蛛。它跨过城墙，像巨兽踏进一座没有退路的城市。",
        sfx="轰!",
        visual_tags=(
            "giant armored desert spider invading a miniature sand fortress",
            "crosshatched red-colony insects swarming its jointed legs",
            "collapsed battlements and disciplined defenders",
            "glass arena viewed like a colossal siege",
            "no extra human figure",
        ),
        characters=("西蒙·克雷斯",),
        actions=("leans over the siege with one hand gripping the glass rim",),
        expressions=("predatory excitement",),
    ),
    SandkingsPageBeat(
        turning_point="沙王把蜘蛛拖入地下，城堡神像露出恶毒笑容",
        purpose="第一次让沙王对克雷斯的判断与仇恨可见",
        shot="extreme close-up with mirrored layers",
        narration="蜘蛛消失在地下。城墙上的神仍有克雷斯的脸，只是那笑容已变成了判决。",
        sfx="咔、咔",
        visual_tags=(
            "dead spider legs disappearing into a sand tunnel",
            "hundreds of insects hauling prey below ground",
            "malicious carved male face in a crumbling fortress wall",
            "real human eye and carved eye aligned through glass reflection",
            "psychological horror composition",
        ),
        characters=("西蒙·克雷斯", "贾拉·沃"),
        actions=(
            "touches the glass while staring at his distorted stone likeness",
            "appears as a small warning hologram pointing toward the changed face",
        ),
        expressions=("anger concealing sudden fear", "grave certainty"),
        relationship_action="the ignored warning returns through the cruel carved portrait",
    ),
    SandkingsPageBeat(
        turning_point="连续挑战失败后，卡茜警告克雷斯必须悬崖勒马",
        purpose="在灾难前给主角最后一次主动停止的机会",
        shot="tense two-shot across trophy debris",
        narration="银蛇、黑鸟、甲壳虫都成了战利品。卡茜再次登门: 总得有人让你停下来。",
        sfx="砰",
        visual_tags=(
            "alien manor trophy room beside glass habitat",
            "discarded silver serpent skin black feathers and cracked beetle shell",
            "unpaid betting notes scattered across a table",
            "ominous carved face watching from the sand castle",
        ),
        characters=("西蒙·克雷斯", "卡茜·穆雷"),
        actions=(
            "dismisses the warning with an open mocking gesture",
            "plants both hands on the table and demands that the games stop",
        ),
        expressions=("amused contempt", "controlled furious resolve"),
        relationship_action="the dissenter offers one last warning and the collector rejects it",
    ),
    SandkingsPageBeat(
        turning_point="克雷斯行贿摆脱查禁，并策划用小狗录像报复卡茜",
        purpose="表现他利用财富逃避后果并把报复扩展到无辜生命",
        shot="noir desk-lamp composition",
        narration="两千元买走了法律的目光。灯灭后，克雷斯开始为卡茜准备一份更残忍的回礼。",
        sfx="咔嗒",
        visual_tags=(
            "dark retrofuturist study under a single hard lamp",
            "sealed payment transfer device beside an official citation",
            "small dog visible safely behind recording glass",
            "camera rig aimed toward the habitat",
            "villainous revenge plan without graphic harm",
        ),
        characters=("西蒙·克雷斯",),
        actions=("programs a recording sequence beside the sealed payment device",),
        expressions=("cold calculating malice",),
    ),
    SandkingsPageBeat(
        turning_point="克雷斯看见丑恶肖像，暴怒刺穿白色城堡并调高湿度",
        purpose="让伪神直接攻击信徒与沙母，越过不可逆界线",
        shot="dynamic spear-thrust dutch angle",
        narration="当白城把他的灵魂刻在墙上，克雷斯举起标枪。神不允许造物说出真相。",
        sfx="咔裂!",
        visual_tags=(
            "long spear piercing a pale organic sand fortress",
            "distorted cruel male face carved across the collapsing wall",
            "every pale insect worker frozen in shock",
            "artificial rain beginning inside the habitat",
            "hidden giant maw convulsing beneath wet sand",
        ),
        characters=("西蒙·克雷斯",),
        actions=(
            "drives a long spear through the white fortress while reaching for humidity controls",
        ),
        expressions=("narcissistic rage",),
    ),
    SandkingsPageBeat(
        turning_point="卡茜带着大锤闯入，决意亲手终止战争游戏",
        purpose="在生态缸破裂前制造最后的正面对峙",
        shot="heroic confrontation low angle",
        narration="卡茜没有再劝。她带着大锤站到鱼缸前，克雷斯则握紧了仍沾着湿沙的标枪。",
        sfx="锵!",
        visual_tags=(
            "storm-lit alien manor laboratory",
            "giant glass habitat cracked but intact",
            "heavy demolition hammer raised beside the tank",
            "wet spear reflecting hard white light",
            "insect armies gathering behind glass",
        ),
        characters=("西蒙·克雷斯", "卡茜·穆雷"),
        actions=(
            "levels the wet spear in panicked defense",
            "raises a heavy hammer toward the glass habitat",
        ),
        expressions=("furious cornered fear", "grim determined courage"),
        relationship_action=(
            "former lovers face each other with the living world trapped between them"
        ),
    ),
    SandkingsPageBeat(
        turning_point="标枪误杀卡茜，生态缸在撞击中彻底破碎",
        purpose="让残酷游戏转化为失控的生存危机",
        shot="explosive diagonal freeze-frame",
        narration="标枪先一步刺出。下一秒，塑料、泥浆和成千上万只沙王像雪崩般冲进宅邸。",
        sfx="轰隆!",
        visual_tags=(
            "giant habitat exploding outward in shards sand and mud",
            "woman falling in silhouette without visible gore",
            "hammer spinning away through the air",
            "four insect armies pouring over the laboratory floor",
            "violent diagonal 1990s comic composition",
        ),
        characters=("西蒙·克雷斯", "卡茜·穆雷"),
        actions=(
            "recoils while still gripping the spear as the tank bursts",
            "falls backward into the collapsing glass wall",
        ),
        expressions=("sudden horrified shock", "final stunned resolve"),
        relationship_action="the shattered habitat erupts between killer and victim",
    ),
    SandkingsPageBeat(
        turning_point="白沙王把卡茜拖入酒窖，克雷斯选择喂养受伤沙母",
        purpose="完成主角从掩盖罪行到主动共谋的道德崩塌",
        shot="deep-focus cellar doorway shot",
        narration="酒窖里，白色工沙搬运着死者。克雷斯没有报警，他把罪证切成了饲料。",
        sfx="窸窣",
        visual_tags=(
            "dark futuristic wine cellar",
            "river of pale insect creatures carrying a covered human form",
            "enormous wounded alien maw breathing beneath the floor",
            "stained cutting tool hidden behind a man's back",
            "non-graphic moral horror",
        ),
        characters=("西蒙·克雷斯",),
        actions=("stands at the cellar threshold offering covered meat to the hidden mother",),
        expressions=("cold dissociated calculation",),
    ),
    SandkingsPageBeat(
        turning_point="毒药失败，杀虫剂软管被咬断，克雷斯险些被反噬",
        purpose="证明普通控制手段已经无效并让猎人首次沦为猎物",
        shot="claustrophobic close action shot",
        narration="毒药没有用。杀虫剂刚喷进地道，软管就在黑暗里被整齐咬断。",
        sfx="噗嗤!",
        visual_tags=(
            "narrow infested manor corridor",
            "severed pesticide hose whipping through the air",
            "dense insect swarm climbing walls and ceiling",
            "respirator and chemical tank thrown aside",
            "black cellar opening behind the fleeing man",
        ),
        characters=("西蒙·克雷斯",),
        actions=("falls backward from the severed hose while insects close around his boots",),
        expressions=("first genuine animal panic",),
    ),
    SandkingsPageBeat(
        turning_point="莉珊德拉带队清剿，沙王用地道陷阱吞没火焰手",
        purpose="展示沙王已具备超越昆虫本能的战场策略",
        shot="cinematic battle wide shot",
        narration="莉珊德拉带来了火焰与装甲。沙王只让地面张开，便把猎人拖进了自己的战术。",
        sfx="轰!",
        visual_tags=(
            "industrial extermination operation inside alien manor",
            "collapsing sand tunnel trap",
            "discarded flamethrower sinking into a swarming pit",
            "red-patterned and black-patterned insect armies retreating in formation",
            "laser cannon cutting through smoke",
        ),
        characters=("西蒙·克雷斯", "莉珊德拉"),
        actions=(
            "points frantically toward the trap while hiding behind armored cover",
            "braces an industrial laser cannon above the collapsing floor",
        ),
        expressions=("cowardly controlling panic", "focused battle discipline"),
        relationship_action="the employer directs the mercenary into a battlefield he created",
    ),
    SandkingsPageBeat(
        turning_point="激光与炸弹摧毁黑、红城堡，白沙母仍在酒窖呼吸",
        purpose="制造虚假胜利并保留真正威胁",
        shot="apocalyptic cutaway splash",
        narration="黑城倒塌，红城熔化。爆炸停下时，酒窖深处那口巨大的呼吸却从未中断。",
        sfx="轰隆——",
        visual_tags=(
            "ruined alien manor opened in dramatic cutaway",
            "two shattered sand fortresses under laser fire",
            "organized insect survivors disappearing into tunnels",
            "untouched pale tunnels descending toward an enormous hidden maw",
            "smoke framed by solid black shadows",
        ),
        characters=("西蒙·克雷斯", "莉珊德拉"),
        actions=(
            "celebrates too early beside the ruined habitat",
            "studies the untouched cellar tunnel with weapon ready",
        ),
        expressions=("desperate false relief", "suspicious tactical focus"),
        relationship_action=(
            "the collector claims victory while the mercenary senses the surviving threat"
        ),
    ),
    SandkingsPageBeat(
        turning_point="白沙王咬伤莉珊德拉，克雷斯推下助手并转枪杀死她",
        purpose="完成克雷斯主动弑人的堕落并暗示沙母的精神影响",
        shot="long corridor betrayal composition",
        narration="酒窖门一开，白色大颚咬穿护套。克雷斯把一个同伴推入黑暗，又把枪口转向另一个。",
        sfx="嗡——砰!",
        visual_tags=(
            "infested gothic cellar corridor",
            "pale alien mandible clamped around an armored wrist",
            "anonymous shadow falling through a black doorway",
            "stolen laser cannon aimed between two figures",
            "white insect swarm covering walls without graphic gore",
        ),
        characters=("西蒙·克雷斯", "莉珊德拉"),
        actions=(
            "aims a stolen laser cannon while backing toward escape",
            "raises her bitten armored hand in furious disbelief",
        ),
        expressions=("frantic murderous terror", "betrayed shock and rage"),
        relationship_action=(
            "the terrified employer betrays the mercenary captain at the cellar mouth"
        ),
    ),
    SandkingsPageBeat(
        turning_point="宅邸成为白沙王巢穴，飞行器被破坏，蜕壳中伸出四只小手",
        purpose="把逃生计划反转为进化揭示",
        shot="surreal multi-depth horror shot",
        narration="飞行器已经死了，宅邸却活了。门后是被他骗来的朋友，脚边的旧壳中伸出四只小手。",
        sfx="喀啦",
        visual_tags=(
            "sabotaged futuristic aircraft outside an infested manor",
            "locked hatch and dead control panel",
            "distant dining-room door bulging with moving shadows",
            "warm alien chrysalis splitting open at the man's feet",
            "exactly four tiny humanoid arms emerging from the shell",
        ),
        characters=("西蒙·克雷斯",),
        actions=("presses both hands against the dead aircraft hatch above the hatching creature",),
        expressions=("desperate existential horror",),
    ),
    SandkingsPageBeat(
        turning_point="沃揭示沙王正在长成两脚四臂的人形，克雷斯向东逃亡",
        purpose="说明进化真相，并让最后逃亡建立在错误方向上",
        shot="split-depth hologram and wasteland shot",
        narration="沃终于说出真相: 它们不是宠物，只是还没有长大。克雷斯向东逃去，却早已失去方向。",
        sfx="滋滋",
        visual_tags=(
            "alien wasteland outside a ruined manor",
            "floating communication hologram showing a two-legged four-armed silhouette",
            "dust storm erasing compass markers",
            "long black road splitting into impossible directions",
            "tiny fleeing figure under a huge dead sky",
        ),
        characters=("西蒙·克雷斯", "贾拉·沃"),
        actions=(
            "runs into the dust while looking back over one shoulder",
            "appears as a grave hologram pointing east beside the four-armed diagram",
        ),
        expressions=("exhausted desperate fear", "urgent controlled concern"),
        relationship_action=(
            "the merchant gives one final route to the man who ignored every warning"
        ),
    ),
    SandkingsPageBeat(
        turning_point="长着克雷斯面孔的橙色四臂幼体抓住并抬走他",
        purpose="让自恋神像变成审判者，以呼吸的黑门完成恐怖闭环",
        shot="nightmare cinematic final wide shot",
        narration="荒野尽头，橙色的孩子找到了他们的神。每一张脸都是克雷斯，而黑色的大门正在呼吸。",
        sfx="呼——吸——",
        visual_tags=(
            "alien desert beneath a solid black sky",
            "circle of small stippled-orange humanoid creatures",
            "every creature has exactly two legs four arms and the same pale angular male face",
            "captured man carried helplessly above them",
            "enormous breathing black doorway in a distant dune",
            "final cosmic horror tableau",
        ),
        characters=("西蒙·克雷斯",),
        actions=("struggles while four-armed children carry him toward the breathing darkness",),
        expressions=("absolute recognition and despair",),
    ),
)
